image: Visual Studio 2017

before_build:
  nuget restore

build:
  publish_wap: true               # package Web Application Projects (WAP) for Web Deploy


# to run tests again only selected assemblies and/or categories
test:
  assemblies:
    - '**/*Tests.dll'
    
after_build:
- cmd: dotnet publish SimpleAspApp --output %appveyor_build_folder%\dist

artifacts:
- path: dist
  name: dist.web