image: Visual Studio 2017

before_build:
  nuget restore

build:
  publish_wap: true               # package Web Application Projects (WAP) for Web Deploy


# to run tests again only selected assemblies and/or categories
test:
  assemblies:
    - '**/*Tests.dll'
    
